### ISSUE TITLE
Query in a stream block: undefined method `check' for nil:NilClass

### ISSUE THREAD

**Issue by carlhoerberg** [jeremyevans/sequel_pg#21]
Do a query inside a stream block against the same db. This is just a stupid example, but will trigger the error: `DB[:plans].stream.each { |r| p DB[:plans][name: r[:name]] }`

```
NoMethodError: undefined method `check' for nil:NilClass
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel_pg-1.6.14/lib/sequel/extensions/pg_streaming.rb:99:in `yield_each_row'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel_pg-1.6.14/lib/sequel/extensions/pg_streaming.rb:99:in `block in fetch_rows'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:175:in `execute'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:525:in `_execute'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel_pg-1.6.14/lib/sequel/extensions/pg_streaming.rb:47:in `_execute'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `execute'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:952:in `execute'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel_pg-1.6.14/lib/sequel/extensions/pg_streaming.rb:98:in `fetch_rows'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:141:in `each'
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel_pg-1.6.14/lib/sequel_pg/sequel_pg.rb:58:in `each'
        from (irb):7
        from /Users/carl/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sequel-4.32.0/bin/sequel:252:in `<top (required)>'
        from /Users/carl/.rbenv/versions/2.3.0/bin/sequel:23:in `load'
        from /Users/carl/.rbenv/versions/2.3.0/bin/sequel:23:in `<main>'
```

**Comment by carlhoerberg** [comment]
Oh, explained in #16
