### ISSUE TITLE
Not compatible with pg 1.1.0

### ISSUE THREAD

**Issue by solnic** [jeremyevans/sequel_pg#27]
I'm getting this after upgrading `pg` from `1.0.0` to `1.1.0`:

```
TypeError: wrong argument type PG::Result (expected Data)
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:679:in `yield_hash_rows'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:679:in `block in fetch_rows'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:155:in `execute'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:514:in `_execute'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:326:in `block (2 levels) in execute'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:536:in `check_database_errors'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:326:in `block in execute'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:326:in `execute'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:1081:in `execute'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/postgres.rb:679:in `fetch_rows'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:154:in `each'
/var/lib/gems/2.4.0/gems/sequel_pg-1.6.19/lib/sequel_pg/sequel_pg.rb:62:in `each'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:465:in `map'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/dataset/actions.rb:465:in `map'
/var/lib/gems/2.4.0/gems/sequel_pg-1.6.19/lib/sequel_pg/sequel_pg.rb:24:in `map'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/shared/postgres.rb:1167:in `pg_class_relname'
/var/lib/gems/2.4.0/gems/sequel-4.48.0/lib/sequel/adapters/shared/postgres.rb:689:in `tables'
```

**Comment by jeremyevans** [comment]
This is already fixed starting in sequel_pg 1.10.0 (commit f95a8ef6dec187a4c2f46e4fbc837e592d0e9698).
