### ISSUE TITLE
Sequel::DatabaseError: PG::UnableToSend: another command is already in progress

### ISSUE THREAD

**Issue by zw963** [jeremyevans/sequel_pg#42]
Following can reproduce on my own project.

my db config:

```rb
DB = Sequel.connect(db_url, timeout: 10000)
if DB.adapter_scheme == :postgres
  DB.extension :pg_streaming
  DB.stream_all_queries = true
end
```

And i write a rake task like this:

```rb
task :update_insider_history_insider_id do
	# a insider history many to one insider (foreign key: insider_id)
	# i want to traversing all `insider histories`, and create insider use name string if not exists, 
	# after create it, then update foreign key insider_id.
	
    InsiderHistory.dataset.each do |ih|
      insider = Insider.find_or_create(name: ih.name)
      ih.update(insider_id: insider.id)
    end
end
```

It works well if comment `DB.stream_all_queries = true` out in db config, but, if not, 
i got following error message.

```
 ╰─ $ rake db:update_insider_history_insider_id
RACK_ENV=development
DB connected: postgres://postgres:postgres@localhost:5432/marketbet_crawler_development
I, [2021-11-09T19:18:00.322859 #1146592]  INFO -- : (0.000271s) SET standard_conforming_strings = ON
I, [2021-11-09T19:18:00.323156 #1146592]  INFO -- : (0.000162s) SET client_min_messages = 'WARNING'
I, [2021-11-09T19:18:00.323363 #1146592]  INFO -- : (0.000129s) SET DateStyle = 'ISO'
I, [2021-11-09T19:18:00.324160 #1146592]  INFO -- : (0.000068s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
I, [2021-11-09T19:18:00.325231 #1146592]  INFO -- : (0.000084s) SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key", "pg_attribute"."attidentity", ("pg_attribute"."attgenerated" != '') AS "generated" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"insider_histories"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
I, [2021-11-09T19:18:00.329566 #1146592]  INFO -- : (0.000040s) SELECT * FROM "insider_histories"
E, [2021-11-09T19:18:00.331996 #1146592] ERROR -- : PG::UnableToSend: another command is already in progress: SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key", "pg_attribute"."attidentity", ("pg_attribute"."attgenerated" != '') AS "generated" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"insiders"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
E, [2021-11-09T19:18:00.332344 #1146592] ERROR -- : PG::UnableToSend: another command is already in progress: SELECT * FROM "insiders" LIMIT 0
rake aborted!
Sequel::DatabaseError: PG::UnableToSend: another command is already in progress
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:81:in `send_query'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:81:in `block in execute_query'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/database/logging.rb:43:in `log_connection_yield'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:81:in `execute_query'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:144:in `block in execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:120:in `check_disconnect_errors'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:144:in `execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:500:in `_execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:47:in `_execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:318:in `block (2 levels) in execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:522:in `check_database_errors'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:318:in `block in execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:318:in `execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/dataset/actions.rb:1093:in `execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:112:in `fetch_rows'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/dataset/actions.rb:152:in `each'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel_pg/sequel_pg.rb:81:in `each'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/dataset/actions.rb:86:in `columns!'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/dataset/actions.rb:76:in `columns'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:242:in `columns'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:788:in `block (2 levels) in get_db_schema'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:686:in `block in check_non_connection_error'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:201:in `block in transaction'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/database/transactions.rb:195:in `transaction'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:686:in `check_non_connection_error'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:788:in `block in get_db_schema'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:821:in `get_db_schema'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:606:in `set_dataset'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/model/base.rb:869:in `inherited'
/home/zw963/Stocks/marketbet_crawler/app/models/insider.rb:1:in `<top (required)>'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:27:in `require'
/home/zw963/Stocks/marketbet_crawler/lib/tasks/update_db.rake:13:in `block (3 levels) in <top (required)>'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:113:in `block (2 levels) in fetch_rows'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:113:in `yield_each_row'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:113:in `block in fetch_rows'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:146:in `execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:500:in `_execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:47:in `_execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:318:in `block (2 levels) in execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:522:in `check_database_errors'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:318:in `block in execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/adapters/postgres.rb:318:in `execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel-5.50.0/lib/sequel/dataset/actions.rb:1093:in `execute'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel/extensions/pg_streaming.rb:112:in `fetch_rows'
/home/zw963/others/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/sequel_pg-1.14.0/lib/sequel_pg/sequel_pg.rb:79:in `each'
/home/zw963/Stocks/marketbet_crawler/lib/tasks/update_db.rake:12:in `block (2 levels) in <top (required)>'
/home/zw963/others/.rvm/gems/ruby-3.0.2@global/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/zw963/.rvm/gems/ruby-3.0.2@global/bin/ruby_executable_hooks:22:in `eval'
/home/zw963/.rvm/gems/ruby-3.0.2@global/bin/ruby_executable_hooks:22:in `<main>
```

And, i try invoke stream directly instead. (with comment `DB.stream_all_queries = true` out),like this:

```rb
  task :update_insider_history_insider_id do
    require_relative '../../config/environment'
    InsiderHistory.dataset.stream.each do |ih|
      puts '*'*100
      pp ih
      puts '*'*100
      insider = Insider.find_or_create(name: ih.name)
      ih.update(insider_id: insider.id)
    end
  end
```

It still not work, only first records get updated.

```
RACK_ENV=development
DB connected: postgres://postgres:postgres@localhost:5432/marketbet_crawler_development
I, [2021-11-09T20:12:43.467444 #1167811]  INFO -- : (0.000305s) SET standard_conforming_strings = ON
I, [2021-11-09T20:12:43.467778 #1167811]  INFO -- : (0.000208s) SET client_min_messages = 'WARNING'
I, [2021-11-09T20:12:43.468024 #1167811]  INFO -- : (0.000166s) SET DateStyle = 'ISO'
I, [2021-11-09T20:12:43.469202 #1167811]  INFO -- : (0.000372s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
I, [2021-11-09T20:12:43.472419 #1167811]  INFO -- : (0.002543s) SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key", "pg_attribute"."attidentity", ("pg_attribute"."attgenerated" != '') AS "generated" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"insider_histories"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
I, [2021-11-09T20:12:43.474305 #1167811]  INFO -- : (0.000042s) SELECT * FROM "insider_histories"
****************************************************************************************************
#<InsiderHistory @values={:id=>6, :date=>#<Date: 2020-10-19 ((2459142j,0s,0n),+0s,2299161j)>, :name=>"Lucas D Creasy", :title=>"CTO", :number_of_holding=>0, :number_of_shares=>19191, :average_price=>0.22e2, :share_total_price=>0.422202e6, :created_at=>2021-05-25 23:25:46.53774 +0800, :stock_id=>1, :insider_id=>nil}>
****************************************************************************************************
I, [2021-11-09T20:12:43.479718 #1167811]  INFO -- : (0.002737s) SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key", "pg_attribute"."attidentity", ("pg_attribute"."attgenerated" != '') AS "generated" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"insiders"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
I, [2021-11-09T20:12:43.481129 #1167811]  INFO -- : (0.000408s) SELECT * FROM "insiders" WHERE ("name" = 'Lucas D Creasy') LIMIT 1
I, [2021-11-09T20:12:43.481614 #1167811]  INFO -- : (0.000143s) BEGIN
I, [2021-11-09T20:12:43.482143 #1167811]  INFO -- : (0.000322s) INSERT INTO "insiders" ("name") VALUES ('Lucas D Creasy') RETURNING *
I, [2021-11-09T20:12:43.483361 #1167811]  INFO -- : (0.001132s) COMMIT
I, [2021-11-09T20:12:43.483747 #1167811]  INFO -- : (0.000105s) BEGIN
I, [2021-11-09T20:12:43.484450 #1167811]  INFO -- : (0.000486s) UPDATE "insider_histories" SET "insider_id" = 5 WHERE ("id" = 6)
I, [2021-11-09T20:12:43.485495 #1167811]  INFO -- : (0.000974s) COMMIT
```

---------------------

This issue may similar with #38, but i use postgres on Arch linux locally.

```
 ╰─ $ pacman -Qi postgresql
Name            : postgresql
Version         : 13.4-1
Description     : Sophisticated object-relational DBMS
Architecture    : x86_64
URL             : https://www.postgresql.org/
Licenses        : custom:PostgreSQL
Groups          : None
Provides        : None
Depends On      : postgresql-libs>=13.4  krb5  libxml2  readline>=6.0  openssl>=1.0.0  pam  icu  systemd-libs  libldap  llvm-libs  libxslt
Optional Deps   : python2: for PL/Python 2 support [installed]
                  python: for PL/Python 3 support [installed]
                  perl: for PL/Perl support [installed]
                  tcl: for PL/Tcl support [installed]
                  postgresql-old-upgrade: upgrade from previous major version using pg_upgrade
                  logrotate: rotates system logs automatically
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 53.18 MiB
Packager        : Levente Polyak <anthraxx@archlinux.org>
Build Date      : Thu 09 Sep 2021 02:07:50 AM CST
Install Date    : Thu 21 Oct 2021 08:57:41 PM CST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : Signature

```

**Comment by janko** [comment]
I've encountered this issue in the past as well. When streaming, it's not possible to execute other queries on the same connection object, because streaming changes the mode in which the connection operates, so during that any other queries would interrupt that.

One solution would be to use a different connection object for the inner updates, but I don't how I would do that. Let's see what Jeremy will say.

**Comment by jeremyevans** [comment]
Issuing other queries inside Dataset#each on the same connection is not supported at all in Sequel (https://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-each).  There are some adapters where it works, but it isn't supported.

Using a different connection is the way to go for the inner updates. You can use sharding or a separate thread to implement that.

**Comment by zw963** [comment]
```rb
InsiderHistory.all do |ih|
      insider = Insider.find_or_create(name: ih.name)
      ih.update(insider_id: insider.id)
    end
```

use all method directly is working, though, maybe occur out of memory issue when use with big database.
